# Create a GitHub action to email a report from a file at 6 am daily
name: Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Email Report
      uses: dawidd6/action-send-mail@v2
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM: test@xo.com